[tool.ruff]
line-length = 120
target-version = "py313"
exclude = [
    "*/migrations/*",
    ".venv",
    "venv",
    "node_modules",
    ".git",
    "staticfiles",
    "media",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]  # errors, flake8, isort, bugbear, pyupgrade
ignore = []                           # ruff is Black-compatible by default

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]              # export imports are ok
"bricli/settings.py" = ["E501"]       # long lines in config files
"manage.py" = ["F401"]

[tool.black]
line-length = 120
target-version = ["py313"]
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | staticfiles
  | media
  | migrations
)/
'''
