# Generated by Django 5.2.6 on 2025-10-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityLandingPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city_name", models.CharField(max_length=100, verbose_name="Nume oraș")),
                ("city_slug", models.SlugField(max_length=100, verbose_name="Slug oraș")),
                ("profession", models.CharField(max_length=100, verbose_name="Meserie")),
                ("profession_slug", models.SlugField(max_length=100, verbose_name="Slug meserie")),
                ("meta_title", models.CharField(max_length=200, verbose_name="Meta Title")),
                ("meta_description", models.TextField(max_length=300, verbose_name="Meta Description")),
                ("h1_title", models.CharField(max_length=200, verbose_name="H1 Title")),
                ("intro_text", models.TextField(help_text="Primul paragraf", verbose_name="Text intro")),
                (
                    "services_text",
                    models.TextField(help_text="Descriere servicii disponibile", verbose_name="Text servicii"),
                ),
                (
                    "prices_text",
                    models.TextField(
                        blank=True, help_text="Informații despre prețuri orientative", verbose_name="Text prețuri"
                    ),
                ),
                (
                    "how_it_works_text",
                    models.TextField(help_text="Pași pentru găsirea meșterului", verbose_name="Cum funcționează"),
                ),
                ("craftsmen_count", models.IntegerField(default=0, help_text="Ex: 45", verbose_name="Număr meșteri")),
                ("reviews_count", models.IntegerField(default=0, help_text="Ex: 230", verbose_name="Număr review-uri")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City Landing Page",
                "verbose_name_plural": "City Landing Pages",
                "ordering": ["city_name", "profession"],
                "unique_together": {("city_slug", "profession_slug")},
            },
        ),
    ]
