# Generated by Django 5.2.6 on 2025-10-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_citylandingpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityLandingFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=300, verbose_name="Întrebare")),
                ("answer", models.TextField(max_length=1000, verbose_name="Răspuns")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordine")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="core.citylandingpage",
                        verbose_name="Landing Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "City Landing FAQ",
                "verbose_name_plural": "City Landing FAQs",
                "ordering": ["landing_page", "order", "question"],
            },
        ),
    ]
