"""
Management command to populate ALL ServiceCategory with services
Usage: python manage.py populate_all_category_services
"""

from django.core.management.base import BaseCommand
from django.utils.text import slugify

from services.models import Service, ServiceCategory


def make_slug(text: str) -> str:
    """Create ASCII-only slug (remove diacritics for SEO)"""
    return (
        slugify(text, allow_unicode=True)
        .replace("ț", "t")
        .replace("Ț", "T")
        .replace("ș", "s")
        .replace("Ș", "S")
        .replace("ă", "a")
        .replace("â", "a")
        .replace("î", "i")
    )


# Complete service list for ALL 33 categories
SERVICES = {
    "acoperisuri": [
        "Reparații acoperiș țiglă",
        "Reparații acoperiș tablă",
        "Înlocuire țiglă spartă",
        "Montaj jgheaburi / burlane",
        "Hidroizolație terasă",
        "Mansardare",
        "Montaj luminator",
        "Stopare infiltrații",
        "Curățare acoperiș",
        "Montaj parazăpezi",
        "Vopsire tablă",
        "Izolație pod",
        "Ferestre de mansardă",
        "Revizie acoperiș",
        "Streasină și pazie",
    ],
    "amenajari": [
        "Amenajare grădină",
        "Amenajare terasă",
        "Amenajare balcon",
        "Amenajare pod",
        "Amenajare mansardă",
        "Amenajare living",
        "Amenajare dormitor",
        "Amenajare cameră copii",
        "Amenajare birou",
        "Amenajare spații comerciale",
        "Amenajare showroom",
        "Amenajare restaurant",
        "Amenajare cafenea",
        "Amenajare sală fitness",
        "Amenajare spații wellness",
    ],
    "asamblare-montaj": [
        "Asamblare mobilier IKEA",
        "Montaj dulap",
        "Montaj pat",
        "Montaj masă / scaune",
        "Montaj bibliotecă",
        "Montaj dressing",
        "Montaj corpuri suspendate",
        "Fixare TV pe perete",
        "Montaj perdele / galerii",
        "Montaj jaluzele",
        "Montaj ușă interior",
        "Montaj ușă metalică",
        "Montaj glafuri",
        "Montaj polițe",
        "Montaj parchet / plintă",
    ],
    "constructii": [
        "Construcție casă",
        "Construcție anexă",
        "Construcție garaj",
        "Construcție gard",
        "Extindere casă",
        "Fundații",
        "Zidărie",
        "Turnare beton",
        "Structură metalică",
        "Schelet beton",
        "Placă beton",
        "Ziduri de sprijin",
        "Consolidări",
        "Demolare controlată",
        "Săpături și excavări",
    ],
    "curatenie-menaj": [
        "Curățenie generală",
        "Curățenie după constructor",
        "Curățenie apartament",
        "Curățenie casă",
        "Spălat geamuri",
        "Curățenie canapele / tapițerie",
        "Curățenie birouri",
        "Igienizare băi",
        "Curățare gresie/faianță",
        "Curățenie frigidere / cuptoare",
        "Aspirat covoare",
        "Curățenie scară bloc",
        "Dezinfectare",
        "Curățenie periodică",
        "Colectare și evacuare moloz",
    ],
    "demo-category": [
        "Serviciu demo",
    ],
    "demolari-debarasari": [
        "Demolare clădiri",
        "Demolare pereți",
        "Demolare pardoseli",
        "Debarasare apartament",
        "Debarasare casă",
        "Debarasare pod",
        "Debarasare pivniță",
        "Evacuare moloz",
        "Evacuare deșeuri",
        "Transport gunoi",
        "Debarasare șantier",
        "Curățenie după demolare",
        "Tăiere beton",
        "Spargere dale",
        "Demolări selective",
    ],
    "design-interior": [
        "Proiectare 3D",
        "Consultanță design",
        "Alegere paletă culori",
        "Amenajare living",
        "Amenajare dormitor",
        "Amenajare bucătărie",
        "Amenajare baie",
        "Iluminat ambiental",
        "Selectare materiale",
        "Stilizare mobilier",
        "Decor ferestre",
        "Tablouri & accente",
        "Plan mobilier la comandă",
        "Planificare spațiu",
        "Studiu de concept",
    ],
    "electricitate": [
        "Tragere circuite noi",
        "Înlocuire tablou electric",
        "Montaj prize și întrerupătoare",
        "Montaj corpuri de iluminat",
        "Montaj siguranțe automate",
        "Priză pentru cuptor / plită",
        "Priză exterior IP65",
        "Împământare / paratrăsnet",
        "Diode / redresor pentru LED",
        "Detectare și remediere scurtcircuit",
        "Rețea cat6 în apartament",
        "TV / coaxial cablare",
        "Smart home (relee / becuri)",
        "Certificat PRAM",
        "Audit energetic locuință",
    ],
    "finisaje": [
        "Zugrăvit pereți",
        "Vopsit pereți",
        "Gletuit",
        "Montaj tapet",
        "Montaj parchet",
        "Montaj gresie",
        "Montaj faianță",
        "Montaj plintă",
        "Montaj lambriuri",
        "Șapă autonivelantă",
        "Tencuieli decorative",
        "Vopsitorie lemn",
        "Lac pentru parchet",
        "Finisaje scări",
        "Profile decorative",
    ],
    "geamuri-ferestre": [
        "Montaj termopan",
        "Reglaj ferestre",
        "Schimbare balamale",
        "Schimbare garnituri",
        "Înlocuire sticlă",
        "Plase insecte",
        "Glafuri interior/exterior",
        "Geamuri culisante",
        "Uși PVC",
        "Uși glisante",
        "Reparații rulouri",
        "Etanșare ferestre",
        "Jaluzele verticale",
        "Jaluzele orizontale",
        "Măsurători & consultanță",
    ],
    "gradinarit-peisagistica": [
        "Tuns gazon",
        "Montaj rulouri gazon",
        "Sisteme irigații",
        "Toaletare arbori",
        "Plantare arbori / arbuști",
        "Însămânțare gazon",
        "Modelare teren",
        "Pavaj alei grădină",
        "Gard viu - plantare și tăiere",
        "Întreținere grădină",
        "Fertilizare",
        "Stropiri fitosanitare",
        "Îndepărtare resturi vegetale",
        "Fântână arteziană mică",
        "Iluminat grădină",
    ],
    "it-tehnologie": [
        "Instalare Windows",
        "Instalare și configurare software",
        "Curățare virus/malware",
        "Recuperare date (basic)",
        "Upgrade SSD/RAM",
        "Rețea Wi-Fi optimizare",
        "Partajare imprimantă",
        "Back-up automat",
        "Monitorizare PC familie",
        "Configurare NAS",
        "Server media (Plex)",
        "Montaj router mesh",
        "Instalare cameră IP",
        "Configurare smart home",
        "Depanare la distanță",
    ],
    "instalatii": [
        "Instalații sanitare complete",
        "Instalații termice",
        "Instalații gaze",
        "Instalații apă rece/caldă",
        "Instalații canalizare",
        "Instalații climatizare",
        "Instalații ventilație",
        "Instalații pompă căldură",
        "Instalații panouri solare",
        "Instalații recuperatoare căldură",
        "Instalații piscine",
        "Instalații irigații",
        "Instalații stingere incendiu",
        "Instalații aspirație centralizată",
        "Instalații gaz metan",
    ],
    "instalatii-electrice": [
        "Tragere circuite noi",
        "Înlocuire tablou electric",
        "Montaj prize și întrerupătoare",
        "Montaj corpuri de iluminat",
        "Montaj siguranțe automate",
        "Priză pentru cuptor / plită",
        "Priză exterior IP65",
        "Împământare / paratrăsnet",
        "Diode / redresor pentru LED",
        "Detectare și remediere scurtcircuit",
        "Rețea cat6 în apartament",
        "TV / coaxial cablare",
        "Smart home (relee / becuri)",
        "Certificat PRAM",
        "Audit energetic locuință",
    ],
    "instalatii-sanitare": [
        "Montaj chiuvetă",
        "Montaj vas WC",
        "Montaj cabină duș",
        "Montaj cadă",
        "Înlocuire țevi (PPR/PEX)",
        "Reparație scurgeri",
        "Montaj baterie",
        "Desfundare canalizare",
        "Montaj boiler",
        "Instalare pompă submersibilă",
        "Montaj apometru",
        "Întreținere țevi",
        "Înlocuire sifon",
        "Verificare etanșeitate",
        "Mutare puncte apă",
        "Montaj mașină de spălat",
    ],
    "instalatii-incalzire": [
        "Montaj centrală termică",
        "Montaj calorifere",
        "Montaj sistem încălzire podea",
        "Montaj pompă căldură",
        "Montaj panouri radiante",
        "Montaj șemineu cu insert",
        "Instalare sobă teracotă",
        "Montaj convectoare",
        "Montaj radiatoare electrice",
        "Service centrală",
        "Curățare centrală",
        "Revizii termice",
        "Echilibrare instalație",
        "Montaj vană termostată",
        "Izolație țevi încălzire",
    ],
    "lucrari-metalice": [
        "Confecții metalice",
        "Balustrade metal",
        "Garduri metalice",
        "Porți metalice",
        "Uși metalice",
        "Scări metalice",
        "Pergole metalice",
        "Copertine metalice",
        "Sudură",
        "Fier forjat",
        "Confecții inox",
        "Șarpante metalice",
        "Structuri metalice",
        "Reparații confecții metalice",
        "Vopsire metal",
    ],
    "mutari-transport": [
        "Mutări apartamente",
        "Mutări case",
        "Mutări birouri",
        "Transport marfă",
        "Transport mobilier",
        "Transport electroc asnice",
        "Dezmembrare / asamblare mobilier",
        "Ambalare profesională",
        "Lift exterior",
        "Depozitare temporară",
        "Mutări internaționale",
        "Transport pianină",
        "Mutări cu asigurare",
        "Mutări urgente",
        "Evacuare moloz",
    ],
    "parchet-gresie": [
        "Montaj parchet masiv",
        "Montaj parchet laminat",
        "Montaj parchet triplu stratificat",
        "Montaj gresie",
        "Montaj faianță",
        "Montaj mozaic",
        "Montaj piatră naturală",
        "Șlefuire parchet",
        "Lacuire parchet",
        "Reparație parchet",
        "Nivelare șapă",
        "Montaj plintă",
        "Montaj profile finisare",
        "Montaj pardoseală vinil (LVT)",
        "Montaj epoxidică",
    ],
    "pavaje-alei": [
        "Pavaje beton",
        "Pavaje piatră naturală",
        "Pavaje gresie exterior",
        "Pavaje dalaj",
        "Alei pietruite",
        "Alei betonare",
        "Alei pavele autoblocante",
        "Borduri",
        "Rigole",
        "Nivelare teren",
        "Fundație pavaj",
        "Compactare",
        "Terase exterioare",
        "Platforme auto",
        "Trotuare",
    ],
    "pictura-vopsitorie": [
        "Vopsit pereți",
        "Zugrăvit",
        "Vopsit tavan",
        "Vopsit lemn",
        "Vopsit metal",
        "Lac pentru lemn",
        "Vopsitorie auto",
        "Grunduire",
        "Tencuieli decorative",
        "Efecte decorative",
        "Vopsit uși",
        "Vopsit ferestre",
        "Vopsit mobilier",
        "Vopsit radiatori",
        "Îndepărtare vopsea veche",
    ],
    "piscine": [
        "Construcție piscine",
        "Montaj piscine prefabricate",
        "Instalații filtrare",
        "Instalații încălzire piscine",
        "Montaj acoperire piscine",
        "Hidroizolație piscine",
        "Montaj faiață piscine",
        "Echipamente piscine",
        "Curățare piscine",
        "Întreținere piscine",
        "Reparații piscine",
        "Sisteme salinizare",
        "Iluminat subacvatic",
        "Terase piscine",
        "Piscine naturale",
    ],
    "renovari": [
        "Renovare apartament",
        "Renovare casă",
        "Renovare baie",
        "Renovare bucătărie",
        "Renovare living",
        "Renovare dormitor",
        "Renovare mansardă",
        "Renovare pod",
        "Renovare clădiri vechi",
        "Modernizare apartament",
        "Renovare bloc",
        "Renovare scară bloc",
        "Renovare spații comerciale",
        "Renovare birouri",
        "Renovare complete",
    ],
    "renovari-constructii": [
        "Renovare baie",
        "Renovare bucătărie",
        "Zugrăvit / vopsit",
        "Gletuit și finisaje",
        "Montaj parchet laminat",
        "Montaj gresie și faianță",
        "Compartimentări din rigips",
        "Tencuieli mecanizate",
        "Șapă și nivelare",
        "Izolație termică / fonică",
        "Montaj uși interioare",
        "Montaj ferestre termopan",
        "Reparații acoperiș",
        "Extinderi și anexe",
        "Consolidări structurale",
        "Placări decorative",
        "Montaj plintă",
    ],
    "reparatii-auto": [
        "Reparații mecanice",
        "Reparații electrică auto",
        "Schimb ulei",
        "Reparații motor",
        "Reparații transmisie",
        "Reparații suspensie",
        "Reparații frâne",
        "Reparații aer condiționat",
        "Geometrie roți",
        "Diagnosticare electronică",
        "Revizie periodică",
        "ITP pregătire",
        "Reparații caroserie",
        "Vopsitorie auto",
        "Reparații geamuri auto",
    ],
    "sanitare": [
        "Montaj chiuvetă",
        "Montaj vas WC",
        "Montaj cabină duș",
        "Montaj cadă",
        "Înlocuire țevi",
        "Reparație scurgeri",
        "Montaj baterie",
        "Desfundare canalizare",
        "Montaj boiler",
        "Instalare pompă",
        "Montaj apometru",
        "Întreținere țevi",
        "Înlocuire sifon",
        "Verificare etanșeitate",
        "Mutare puncte apă",
    ],
    "sticlarie": [
        "Montaj geamuri",
        "Tăiere sticlă",
        "Geamuri securizate",
        "Geamuri termopan",
        "Geamuri tripan",
        "Montaj oglinzi",
        "Tăiere oglinzi",
        "Balustrade sticlă",
        "Dulapuri oglindă",
        "Vitrină sticlă",
        "Sticlă laminată",
        "Sticlă mată",
        "Sticlă colorată",
        "Reparații geamuri",
        "Etanșare geamuri",
    ],
    "tapiterie-decoratiuni": [
        "Tapițare canapele",
        "Tapițare fotolii",
        "Tapițare scaune",
        "Confecții perdele",
        "Confecții draperii",
        "Confecții huse",
        "Montaj mochete",
        "Montaj covoare",
        "Reparații tapițerie",
        "Schimbare bureți",
        "Confecții textile",
        "Decorațiuni interioare",
        "Perne decorative",
        "Capitonaj",
        "Cuie tapițerie",
    ],
    "tamplarie": [
        "Uși interior lemn",
        "Uși exterior lemn",
        "Ferestre lemn",
        "Mobilier la comandă",
        "Bucătării la comandă",
        "Dulapuri la comandă",
        "Birouri lemn",
        "Biblioteci lemn",
        "Mese lemn",
        "Scaune lemn",
        "Parchet masiv",
        "Lambriuri lemn",
        "Pergole lemn",
        "Foisoare lemn",
        "Reparații tâmplărie",
    ],
    "tamplarie-dulgherie": [
        "Uși interior",
        "Uși exterior",
        "Ferestre lemn",
        "Mobilier la comandă",
        "Bucătării la comandă",
        "Dulapuri",
        "Dressing-uri",
        "Birouri lemn",
        "Biblioteci",
        "Scări lemn",
        "Balustrade lemn",
        "Parchet masiv",
        "Lambriuri",
        "Reparații mobilier",
        "Șlefuire și lac",
    ],
    "zidarie-beton": [
        "Zidărie cărămidă",
        "Zidărie BCA",
        "Zidărie piatră",
        "Turnare beton",
        "Șape beton",
        "Fundații",
        "Stâlpi beton",
        "Grinzi beton",
        "Plăci beton",
        "Tencuieli",
        "Tencuieli mecanizate",
        "Reparații beton",
        "Forare beton",
        "Tăiere beton",
        "Demolare beton",
    ],
    "seminee-cosuri": [
        "Construcție șeminee",
        "Montaj șemineu prefabricat",
        "Montaj insert șemineu",
        "Montaj sobă teracotă",
        "Construcție coș fum",
        "Curățare coș fum",
        "Reparații șeminee",
        "Reparații coșuri",
        "Hidroizolație coș",
        "Montaj racord coș",
        "Montaj căpăcel coș",
        "Termoizolație coș",
        "Verificare traseu coș",
        "Modernizare șemineu",
        "Service sobă",
    ],
}


class Command(BaseCommand):
    help = "Populate ALL categories with services (comprehensive)"

    def handle(self, *args, **opts):
        created_svcs = 0
        updated_svcs = 0

        self.stdout.write("Populating services for all categories...")

        # Get all active categories
        categories = ServiceCategory.objects.filter(is_active=True)

        for category in categories:
            slug = category.slug
            service_list = SERVICES.get(slug, [])

            if not service_list:
                self.stdout.write(self.style.WARNING(f"[!] No services defined for: {slug}"))
                continue

            self.stdout.write(f"\nProcessing: {slug} ({len(service_list)} services)")

            for service_name in service_list:
                s_slug = f"{slug}-{make_slug(service_name)}"

                svc, svc_created = Service.objects.get_or_create(
                    slug=s_slug,
                    defaults={
                        "category": category,
                        "name": service_name,
                        "is_popular": True,
                        "is_active": True
                    },
                )

                if svc_created:
                    created_svcs += 1
                    # Skip detailed output to avoid encoding issues
                else:
                    # Update existing service to mark as popular
                    changed = False
                    if not svc.is_popular:
                        svc.is_popular = True
                        changed = True
                    if not svc.is_active:
                        svc.is_active = True
                        changed = True
                    if svc.category != category:
                        svc.category = category
                        changed = True

                    if changed:
                        svc.save()
                        updated_svcs += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone! Created {created_svcs} services, updated {updated_svcs} services."
            )
        )
        self.stdout.write(
            f"Total in DB: {ServiceCategory.objects.count()} categories, {Service.objects.count()} services"
        )
