# Generated by Django 5.2.6 on 2025-09-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_km', models.PositiveSmallIntegerField(default=30, help_text='Raza de acoperire în km')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_city', models.ForeignKey(help_text='Orașul de bază', on_delete=django.db.models.deletion.PROTECT, to='accounts.city')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='accounts.craftsmanprofile')),
            ],
            options={
                'verbose_name': 'Zonă de acoperire',
                'verbose_name_plural': 'Zone de acoperire',
            },
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cents', models.IntegerField(default=0, help_text='Soldul în bani (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(help_text='Suma în bani (cents) - pozitivă pentru încărcare, negativă pentru taxe')),
                ('reason', models.CharField(choices=[('top_up', 'Încărcare credit'), ('lead_fee', 'Taxă lead (shortlist)'), ('refund', 'Rambursare'), ('bonus', 'Bonus'), ('adjustment', 'Ajustare')], max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Date suplimentare (order_id, client_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.creditwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('accepted', 'Acceptată'), ('declined', 'Refuzată')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='services.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'craftsman')},
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_fee_amount', models.PositiveIntegerField(default=0, help_text='Taxa în bani (cents)')),
                ('charged_at', models.DateTimeField(blank=True, help_text='Când s-a deductat taxa', null=True)),
                ('revealed_contact_at', models.DateTimeField(blank=True, help_text='Când s-au afișat datele de contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_for', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='services.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'craftsman')},
            },
        ),
    ]
