# Generated by Django 5.2.6 on 2025-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_coveragearea_creditwallet_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Când meșterul a confirmat preluarea', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_at',
            field=models.DateTimeField(blank=True, help_text='Când clientul a selectat meșterul', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_quote', 'Ofertă nouă'), ('quote_accepted', 'Ofertă acceptată'), ('quote_rejected', 'Ofertă respinsă'), ('order_published', 'Comandă publicată'), ('order_completed', 'Comandă finalizată'), ('order_confirmed', 'Comandă confirmată de meșter'), ('order_declined', 'Comandă refuzată de meșter'), ('review_received', 'Recenzie primită')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Ciornă'), ('published', 'Publicată'), ('awaiting_confirmation', 'Așteaptă confirmarea meșterului'), ('in_progress', 'În progres'), ('completed', 'Finalizată'), ('cancelled', 'Anulată')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('accepted', 'Acceptată'), ('rejected', 'Respinsă'), ('declined', 'Refuzată de meșter'), ('expired', 'Expirată')], default='pending', max_length=10),
        ),
    ]
