# Generated by Django 5.2.6 on 2025-10-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_database_indexes'),
        ('services', '0005_paymentintent_paymentmethod_stripecustomer'),
    ]

    operations = [
    ]
