# Generated by Django 5.2.6 on 2025-10-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_merge_20251001_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
