# Generated by Django 5.2.6 on 2025-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_remove_legacy_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="service",
            name="is_popular",
            field=models.BooleanField(default=False, help_text="Popular service shown in suggestions"),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="icon_emoji",
            field=models.CharField(default="🔧", help_text="Emoji icon for category", max_length=8),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
