# Generated by Django 5.2.6 on 2025-10-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_add_icon_emoji_and_is_popular"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="quote_attachments/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Imagine"), ("pdf", "PDF"), ("document", "Document"), ("other", "Altele")],
                        max_length=20,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(help_text="Mărime fișier în bytes")),
                ("description", models.CharField(blank=True, help_text="Descriere scurtă (opțional)", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="services.quote"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atașament Ofertă",
                "verbose_name_plural": "Atașamente Oferte",
                "ordering": ["created_at"],
            },
        ),
    ]
