# Generated by Django 5.2.6 on 2025-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_quoteattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="proposed_start_date",
            field=models.DateField(
                blank=True,
                help_text="Data la care meșterul propune să înceapă lucrarea",
                null=True,
                verbose_name="Data propusă pornire",
            ),
        ),
    ]
