# Generated by Django 5.2.6 on 2025-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_quote_proposed_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[("hours", "Ore"), ("days", "Zile"), ("weeks", "Săptămâni"), ("months", "Luni")],
                help_text="Unitatea de măsură pentru durată",
                max_length=20,
                null=True,
                verbose_name="Unitate durată",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="duration_value",
            field=models.IntegerField(
                blank=True,
                help_text="Numărul de unități de timp (ex: 5 pentru '5 zile')",
                null=True,
                verbose_name="Valoare durată",
            ),
        ),
    ]
