# Generated by Django 5.2.6 on 2025-10-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_quote_duration_unit_quote_duration_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettransaction",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="paymentintent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="user",
        ),
        migrations.RemoveField(
            model_name="stripecustomer",
            name="user",
        ),
        migrations.DeleteModel(
            name="CreditWallet",
        ),
        migrations.DeleteModel(
            name="WalletTransaction",
        ),
        migrations.DeleteModel(
            name="PaymentIntent",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="StripeCustomer",
        ),
    ]
