# Generated by Django 5.2.6 on 2025-09-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftsmanportfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Imagine Portofoliu', 'verbose_name_plural': 'Imagini Portofoliu'},
        ),
        migrations.AlterModelOptions(
            name='craftsmanprofile',
            options={'verbose_name': 'Profil Meșter', 'verbose_name_plural': 'Profile Meșteri'},
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='service_radius',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='craftsmanportfolio',
            name='flagged_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='craftsmanportfolio',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='craftsmanportfolio',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanportfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Descriere scurtă - ce tip de lucrări faci (minim 200 caractere)', null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='company_cui',
            field=models.CharField(blank=True, help_text="CUI/CIF (dacă e firmă/PFA) - pentru badge 'Firmă înregistrată'", max_length=20),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='company_verified_at',
            field=models.DateTimeField(blank=True, help_text='Data verificării CUI (setat automat)', null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='coverage_radius_km',
            field=models.PositiveSmallIntegerField(default=25, help_text='Raza de acoperire în km (5-150)'),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nume afișat (nume persoană sau denumire comercială)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook'),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram'),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='is_company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='min_job_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valoare minimă lucrare (lei)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='profile_completion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Poză de profil', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Site web'),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ani de experiență', null=True),
        ),
        migrations.AlterField(
            model_name='craftsmanportfolio',
            name='description',
            field=models.TextField(blank=True, help_text='Descriere lucrare (opțional)', max_length=500),
        ),
        migrations.AlterField(
            model_name='craftsmanportfolio',
            name='image',
            field=models.ImageField(help_text='Poză cu lucrarea (fără fețe/date personale vizibile)', upload_to='portfolio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='craftsmanportfolio',
            name='title',
            field=models.CharField(blank=True, help_text='Titlu lucrare (opțional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.county'),
        ),
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif orientativ (lei/oră)', max_digits=8, null=True),
        ),
    ]
