# Generated by Django for performance optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_craftsmanportfolio_options_and_more'),
    ]

    operations = [
        # Add indexes for CraftsmanProfile model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_craftsman_county_city ON accounts_craftsmanprofile(county_id, city_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_craftsman_county_city;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_craftsman_rating ON accounts_craftsmanprofile(average_rating DESC, total_reviews DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_craftsman_rating;"
        ),
        
        # Add indexes for User model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_user_type_active ON accounts_user(user_type, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_user_type_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_user_verified ON accounts_user(is_verified, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_user_verified;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_user_email ON accounts_user(email);",
            reverse_sql="DROP INDEX IF EXISTS idx_user_email;"
        ),
    ]