# Generated by Django 5.2.6 on 2025-10-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_database_indexes'),
        ('accounts', '0003_user_backup_codes_user_two_factor_enabled_and_more'),
    ]

    operations = [
    ]
