# Generated by Django 5.2.6 on 2025-10-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251001_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsmanprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefon de contact (opțional)', max_length=15),
        ),
    ]
