# Generated by Django 5.2.6 on 2025-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_craftsmanprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftsmanprofile",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="URL-friendly identifier (auto-generated)",
                max_length=120,
                null=True,
            ),
        ),
    ]
