# Generated by Django 5.2.6 on 2025-10-10 20:29

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing CraftsmanProfile records"""
    CraftsmanProfile = apps.get_model("accounts", "CraftsmanProfile")

    for profile in CraftsmanProfile.objects.all():
        if not profile.slug and profile.display_name:
            base_slug = slugify(profile.display_name, allow_unicode=True)
            slug = base_slug
            counter = 1

            # Ensure uniqueness
            while CraftsmanProfile.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            profile.slug = slug
            profile.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_slug_field"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
    ]
