# Generated by Django 5.2.6 on 2025-10-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_make_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL-friendly slug", max_length=80, unique=True),
        ),
    ]
