# Generated by Django 5.2.6 on 2025-10-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_county_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftsmanprofile",
            name="business_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Adresa sediului firmei/PFA (opțional)",
                max_length=255,
                verbose_name="Adresa sediu (opțional)",
            ),
        ),
    ]
