# Generated by Django 5.2.6 on 2025-10-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_craftsmanprofile_business_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftsmanprofile",
            name="cnp",
            field=models.CharField(
                blank=True,
                help_text="CNP (obligatoriu pentru Persoană Fizică, lăsat gol pentru PFA/SRL)",
                max_length=13,
            ),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="company_name",
            field=models.CharField(blank=True, help_text="Denumire firmă (obligatoriu pentru PFA/SRL)", max_length=200),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="cui",
            field=models.CharField(
                blank=True, help_text="CUI (obligatoriu pentru PFA/SRL, lăsat gol pentru PF)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="fiscal_address_city",
            field=models.CharField(blank=True, help_text="Oraș - obligatoriu pentru facturare", max_length=100),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="fiscal_address_county",
            field=models.CharField(blank=True, help_text="Județ - obligatoriu pentru facturare", max_length=100),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="fiscal_address_postal_code",
            field=models.CharField(blank=True, help_text="Cod poștal", max_length=10),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="fiscal_address_street",
            field=models.CharField(
                blank=True, help_text="Adresă completă (stradă, număr) - obligatoriu pentru facturare", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="fiscal_type",
            field=models.CharField(
                choices=[("PF", "Persoană Fizică"), ("PFA", "PFA/Întreprindere Individuală"), ("SRL", "SRL/SRL-D")],
                default="PF",
                help_text="Tip persoană (obligatoriu pentru facturare)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="phone",
            field=models.CharField(blank=True, help_text="Telefon de contact (format: +407XXXXXXXX)", max_length=20),
        ),
    ]
