# Generated by Django 5.2.6 on 2025-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_craftsmanprofile_cnp_craftsmanprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftsmanprofile",
            name="beta_member",
            field=models.BooleanField(default=False, help_text="Meșter înregistrat în perioada BETA (primii 100)"),
        ),
        migrations.AddField(
            model_name="craftsmanprofile",
            name="beta_registration_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Număr de ordine în programul BETA (1-100)", null=True
            ),
        ),
    ]
