# Generated by Django 5.2.6 on 2025-10-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="method",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp")],
                default="email",
                help_text="Metodă de livrare cod",
                max_length=10,
            ),
        ),
    ]
