# Generated by Django 5.2.6 on 2025-09-23 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins'), ('flagged', 'Marcat pentru verificare')], default='pending', max_length=20)),
                ('has_faces', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagine în moderare',
                'verbose_name_plural': 'Imagini în moderare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.CharField(choices=[('flood', 'Flood/Spam'), ('abuse', 'Abuz'), ('suspicious', 'Activitate suspectă'), ('manual', 'Blocare manuală')], max_length=20)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP blocat',
                'verbose_name_plural': 'IP-uri blocate',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('warning', 'Avertisment'), ('content_removal', 'Ștergere conținut'), ('account_suspension', 'Suspendare cont'), ('account_ban', 'Interzicere cont'), ('profile_restriction', 'Restricție profil')], max_length=30)),
                ('reason', models.TextField()),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acțiune de moderare',
                'verbose_name_plural': 'Acțiuni de moderare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Conținut nepotrivit'), ('fake_profile', 'Profil fals'), ('scam', 'Înșelătorie'), ('harassment', 'Hărțuire'), ('copyright', 'Încălcare drepturi de autor'), ('other', 'Altele')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('reviewing', 'În curs de analiză'), ('resolved', 'Rezolvat'), ('dismissed', 'Respins')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raportare',
                'verbose_name_plural': 'Raportări',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('order_creation', 'Creare comenzi'), ('quote_creation', 'Creare oferte'), ('message_sending', 'Trimitere mesaje'), ('profile_updates', 'Actualizări profil'), ('review_creation', 'Creare recenzii')], max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('max_limit_new_user', models.PositiveIntegerField(default=3)),
                ('max_limit_verified_user', models.PositiveIntegerField(default=10)),
                ('window_hours', models.PositiveIntegerField(default=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limită de utilizare',
                'verbose_name_plural': 'Limite de utilizare',
                'unique_together': {('user', 'limit_type')},
            },
        ),
    ]
