# Generated by Django 5.2.6 on 2025-10-18 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        db_index=True, help_text="Stripe Invoice ID (in_xxx)", max_length=100, unique=True
                    ),
                ),
                ("smartbill_series", models.CharField(help_text="Invoice series (e.g., 'SUBS')", max_length=20)),
                ("smartbill_number", models.CharField(help_text="Invoice number", max_length=50)),
                ("smartbill_url", models.URLField(blank=True, help_text="Public URL to view invoice (if available)")),
                (
                    "total_ron",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount including TVA (e.g., 49.00)", max_digits=10
                    ),
                ),
                (
                    "base_ron",
                    models.DecimalField(
                        decimal_places=2, help_text="Base amount without TVA (e.g., 41.18)", max_digits=10
                    ),
                ),
                (
                    "tva_ron",
                    models.DecimalField(decimal_places=2, help_text="TVA amount at 19% (e.g., 7.82)", max_digits=10),
                ),
                ("client_name", models.CharField(help_text="Client name at time of invoice", max_length=255)),
                ("client_fiscal_code", models.CharField(help_text="CUI or CNP at time of invoice", max_length=20)),
                ("client_address", models.TextField(help_text="Full address at time of invoice")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, help_text="Local copy of PDF invoice", null=True, upload_to="invoices/%Y/%m/"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, help_text="Whether invoice email was sent to client"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when invoice email was sent", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription this invoice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="subscriptions.craftsmansubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["subscription", "created_at"], name="invoice_sub_date_idx"),
                    models.Index(fields=["email_sent"], name="invoice_email_idx"),
                ],
                "unique_together": {("smartbill_series", "smartbill_number")},
            },
        ),
    ]
