# Generated by Django 5.2.6 on 2025-09-30 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_orders', models.BooleanField(default=True, verbose_name='Email pentru comenzi noi')),
                ('email_quotes', models.BooleanField(default=True, verbose_name='Email pentru oferte')),
                ('email_payments', models.BooleanField(default=True, verbose_name='Email pentru plăți')),
                ('email_messages', models.BooleanField(default=True, verbose_name='Email pentru mesaje')),
                ('email_reviews', models.BooleanField(default=True, verbose_name='Email pentru recenzii')),
                ('email_system', models.BooleanField(default=True, verbose_name='Email pentru anunțuri sistem')),
                ('push_new_orders', models.BooleanField(default=True, verbose_name='Push pentru comenzi noi')),
                ('push_quotes', models.BooleanField(default=True, verbose_name='Push pentru oferte')),
                ('push_payments', models.BooleanField(default=True, verbose_name='Push pentru plăți')),
                ('push_messages', models.BooleanField(default=True, verbose_name='Push pentru mesaje')),
                ('push_reviews', models.BooleanField(default=True, verbose_name='Push pentru recenzii')),
                ('push_system', models.BooleanField(default=False, verbose_name='Push pentru anunțuri sistem')),
                ('digest_frequency', models.CharField(choices=[('never', 'Niciodată'), ('daily', 'Zilnic'), ('weekly', 'Săptămânal')], default='daily', max_length=20, verbose_name='Frecvența rezumatului')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Nu trimite notificări push în acest interval', null=True, verbose_name='Ora de început liniște')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Ora de sfârșit liniște')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Preferință notificare',
                'verbose_name_plural': 'Preferințe notificări',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Comandă nouă'), ('order_update', 'Actualizare comandă'), ('new_quote', 'Ofertă nouă'), ('quote_accepted', 'Ofertă acceptată'), ('quote_rejected', 'Ofertă respinsă'), ('payment_received', 'Plată primită'), ('payment_required', 'Plată necesară'), ('review_received', 'Recenzie primită'), ('message_received', 'Mesaj nou'), ('account_verified', 'Cont verificat'), ('system_announcement', 'Anunț sistem'), ('reminder', 'Memento')], max_length=50, verbose_name='Tip notificare')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('priority', models.CharField(choices=[('low', 'Scăzută'), ('normal', 'Normală'), ('high', 'Înaltă'), ('urgent', 'Urgentă')], default='normal', max_length=20, verbose_name='Prioritate')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citită')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (order, quote, message, etc.)', max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL where user should be redirected when clicking notification', null=True, verbose_name='Link acțiune')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat la')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Citit la')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the notification', null=True, verbose_name='Expiră la')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email trimis')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push trimis')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatar')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Expeditor')),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificări',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(verbose_name='Endpoint')),
                ('p256dh_key', models.TextField(verbose_name='Cheie P256DH')),
                ('auth_key', models.TextField(verbose_name='Cheie Auth')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat la')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima utilizare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Abonament Push',
                'verbose_name_plural': 'Abonamente Push',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
